ClassIsland/App.xaml.cs
ClassIsland/ClassIsland.csproj
ClassIsland/Controls/MiniInfoProvider/CountDownMiniInfoProviderControl.xaml
ClassIsland/Controls/MiniInfoProvider/CountDownMiniInfoProviderControl.xaml.cs
ClassIsland/Controls/MiniInfoProvider/CountDownMiniInfoProviderSettingsControl.xaml
ClassIsland/Controls/MiniInfoProvider/CountDownMiniInfoProviderSettingsControl.xaml.cs
ClassIsland/Converters/DateTimeToDaysLeftConverter.cs
ClassIsland/Models/CountDownMiniInfoProviderSettings.cs
ClassIsland/Services/MiniInfoProviders/CountDownMiniInfoProvider.cs

实现了Issue #60 中的倒计时功能
经本地测试，暂未发现bug

[功能更新] 新增倒计时功能

---

ClassIsland/Controls/MiniInfoProvider/CountDownMiniInfoProviderControl.xaml
ClassIsland/Controls/MiniInfoProvider/CountDownMiniInfoProviderSettingsControl.xaml
ClassIsland/Converters/DateTimeToDaysLeftConverter.cs
ClassIsland/Models/CountDownMiniInfoProviderSettings.cs
ClassIsland/RegistryNotifier.cs

1.修正@HelloWRC在注释中的错字（
2.[功能更新]倒计时功能添加字体颜色与字体大小的设定

[功能更新]倒计时功能新增字体颜色与字体大小的设置

---

README.md

更正AppVeyer链接

---

ClassIsland/Views/SettingsWindow.xaml

修正第三方库引用链接

---

ClassIsland.Core/Extensions/FilePathExtensions.cs
ClassIsland/App.xaml.cs
ClassIsland/MainWindow.xaml
ClassIsland/MainWindow.xaml.cs
ClassIsland/Models/Settings.cs
ClassIsland/Services/FileFolderService.cs

有部分逻辑打包成方法放在 FileFolderService 里了，不确定放在那里合不合适。
没有足够的分区进行测试，不能保证其是否稳定。

检查程序目录是否为桌面，并提示移动

---

ClassIsland.Core/Converters/DateTimeDeltaToCanvasPosConverter.cs
ClassIsland/Behaviors/TimeLineListItemBehavior.cs
ClassIsland/Controls/TimeLineListItemExpandingAdornerControl.xaml
ClassIsland/Controls/TimeLineListItemExpandingAdornerControl.xaml.cs
ClassIsland/Themes/Generic.xaml
ClassIsland/Views/ProfileSettingsWindow.xaml
ClassIsland/Views/ProfileSettingsWindow.xaml.cs

优化时间线视图下的编辑体验

---

README.md

这个修改参考的是 WRC 发表在小众软件的文章，主要的设计思路是「怎么让用户被 ClassIsland 所吸引」，同时能保留 Readme 原有的功能性。
修改方向如下：
1. 引导用户到 Bilibili 或官网，通过网页或视频更好地展现软件。
2. 将具体的功能交给 ClassIsland 文档来讲述。
3. 展示 ClassIsland 优雅的界面。
4. 引导用户下载体验 ClassIsland。
5. 为用户提供更详细的下载和获取帮助指引。
6. 引导用户加入 QQ 群以增进互动。
使用了[@LiuYan-xwx](https://github.com/LiuYan-xwx/ClassIsland/blob/patch/README.md#亮点) 录制的软件截图，在此表示感谢。
经过测试，在手机版视图上表现良好。
**要预览修改后的效果，请前往 https://github.com/DryIce-cc/ClassIsland**
“相关项目”条目被删除，加了个 Stars 的条目，如果不合适可以恢复。
图片的上传方式如果不正确，请帮助修改。
有部分修改过于激进（比如大段居中），或不符合 Github Readme 常理，还请多多指正。

修改 Readme.md

---

.all-contributorsrc
README.md

doc: 更新贡献者名单

---

.github/ISSUE_TEMPLATE/BugReport.yml
.github/ISSUE_TEMPLATE/FeatureRequest.yml
.github/ISSUE_TEMPLATE/config.yml
README.md

**要预览修改后的效果，请前往 https://github.com/DryIce-cc/ClassIsland/issues/new/choose**
主要更新：
1. 更新 tag 以适配新名称
次要更新：
1. 去除了 assignees（这个有什么用吗？
2. 去除了标题中的 [Bug]: [功能请求]: （有 tag 应该也够了吧
3. 使一大段检查清单不再出现在正文中
4. 要求用户更新到最新测试版再反馈（还是说要保留正式版的反馈？
5. 把 Windows 版本信息设为非必要（大部分 Bug 应该都与系统无关，所以只是提了一句
6. 稍微修正了一下 README.md 中的错误

修改 Issue 模版

---

.github/ISSUE_TEMPLATE/BugReport.yml
.github/ISSUE_TEMPLATE/FeatureRequest.yml
README.md

style: 优化 readme 以及 issue template 排版

---

ClassIsland/Views/SettingPages/GeneralSettingsPage.xaml

优化设置界面隐藏窗口card的布局

---

examples/example.json

fix: 修复错别字

---

ClassIsland/App.xaml.cs
ClassIsland/Models/Settings.cs
ClassIsland/ViewModels/MainViewModel.cs
ClassIsland/Views/SettingPages/DebugPage.xaml
ClassIsland/Views/SettingPages/DebugPage.xaml.cs
ClassIsland/Views/SettingPages/GeneralSettingsPage.xaml

另外推荐一下 [LyCecilion 档案中的 ClassIsland 介绍](https://github.com/LyCecilion/LyCecilion?tab=readme-ov-file#-classisland) ，加入了 ✨🥳🥵💻📚🐧 和五颜六色的
[![view - Documentation](https://img.shields.io/badge/view-Documentation-blue)](https://classisland.github.io/classisland-docs-next)
可使 Readme 更为活泼并提升易读性（）
~这次真的完全没有在代码里到处乱改了斯米马赛~

新功能：允许在发生灾难时直接退出而不弹出错误窗口

---

README.md

1.把“classlsland QQ频道“链接移至上方并加大（
2.把classlsland最新的投票地址添加到“原QQ频道”处
3.把上面的classlsland给添加“官方”二字

添加了新链接和部分排版01

---

ClassIsland/Controls/Components/CountDownComponent.xaml
ClassIsland/Controls/Components/CountDownComponent.xaml.cs

fix: 修改倒计时数字与汉字间的 margin

---

ClassIsland/MainWindow.xaml
ClassIsland/Models/Settings.cs
ClassIsland/Views/SettingPages/AppearanceSettingsPage.xaml

Complete #404 
同时还修改了一些外观设置的描述（）（统一描述）
完成细节见 commit 信息
效果如图：

自定义背景颜色 Complete #404

---

ClassIsland.Core/Controls/LessonsControls/ClassInfoMultiConverter.cs
ClassIsland.Core/Controls/LessonsControls/LessonControlExpanded.xaml
ClassIsland.Core/Controls/LessonsControls/LessonControlMinimized.xaml
ClassIsland.Core/Controls/LessonsControls/LessonsListBox.cs
ClassIsland.Shared/Models/Profile/ClassPlan.cs
ClassIsland.Shared/Models/Profile/Profile.cs
ClassIsland/Controls/Components/ScheduleComponent.xaml
ClassIsland/Controls/Components/ScheduleComponentSettingsControl.xaml
ClassIsland/Models/ComponentSettings/LessonControlSettings.cs
ClassIsland/Services/LessonsService.cs
ClassIsland/Themes/DarkTheme.xaml
ClassIsland/Themes/LightTheme.xaml
ClassIsland/Views/FeatureDebugWindow.xaml

总算把标记换课课程的这块逻辑挪出来了（
~虽然还是不知道这个逻辑到底怎么写。。。~

pref: 优化标记换课课程

---

ClassIsland.Core/Abstractions/Services/IWeatherService.cs
ClassIsland.Core/Models/Weather/CityInfo.cs
ClassIsland/Models/Settings.cs
ClassIsland/Services/WeatherService.cs
ClassIsland/ViewModels/SettingsPages/WeatherSettingsViewModel.cs
ClassIsland/Views/SettingPages/WeatherSettingsPage.xaml
ClassIsland/Views/SettingPages/WeatherSettingsPage.xaml.cs

移除本地的城市key数据库的相关代码，使用小米天气的API来搜索城市
（其实是因为我所在市的区搜不到，但是APP上又能搜到，所以才弄的）
- 搜索城市的name为空时，使用最热搜索城市（热搜）
- 搜索城市的name不为空时，调用小米天气搜索城市的API
- 搜索有使用防抖，时间间隔为50毫秒

feat: 移除本地的城市key数据库，使用小米天气API搜索城市

---

ClassIsland.Core/Models/Weather/CityInfo.cs
ClassIsland/Services/WeatherService.cs

先通过`LocationKey`即`CityId`来获取`经纬度`信息，在请求`天气信息`的时候附带上`经纬度`信息，有望提高天气精度
- feat(CityInfo): 获取经纬度信息
- feat(WeatherService): 先获取`经纬度`再获取`天气信息`

feat: 小米天气API，通过附带经纬度信息尝试提高天气精度

---

ClassIsland.Core/Models/Weather/ForecastDaily.cs

- 可以用于深浅色自动切换
- 或者日出日落的时间组件 #594

feat(ForecastDaily): 获取日出日落数据

---

ClassIsland/App.xaml.cs
ClassIsland/Views/CrashWindow.xaml
ClassIsland/Views/CrashWindow.xaml.cs

feat: cute-crashwindow

---

ClassIsland.Core/Controls/LessonsControls/LessonsListBox.cs
ClassIsland.Core/Controls/LessonsControls/LessonsListBox.xaml
ClassIsland.Core/Controls/LessonsControls/LessonsListBoxItemTemplateMultiConverter.cs
ClassIsland/Controls/Components/ScheduleComponent.xaml
ClassIsland/Controls/Components/ScheduleComponentSettingsControl.xaml
ClassIsland/Models/ComponentSettings/LessonControlSettings.cs

萌新第一个PR，不太懂dotnet，但也算是为实现自己的需求，完全是照葫芦画瓢改了改：D
这个PR有任何不妥还希望各位devs能多多指出！
closes https://github.com/ClassIsland/ClassIsland/issues/193

feat: 支持不显示已结束的课程

---

ClassIsland/ViewModels/WelcomeViewModel.cs

This reverts commit b8dab50aa454b7de5bb52759bead18c0b86fbea8. 
我认为一是注册了之后体验会更好，目前一些地方都在使用url协议；二是注册了也不会有什么坏处

Revert "使开始界面的`注册Url协议`不默认勾选"

---

ClassIsland/Views/SettingPages/NotificationSettingsPage.xaml.cs

feat: 添加流萤TTS选项

---

ClassIsland/Views/SettingPages/NotificationSettingsPage.xaml.cs

feat: 添加三月七TTS选项

---

ClassIsland/ViewModels/SettingsPages/PluginsSettingsPageViewModel.cs
ClassIsland/Views/SettingPages/PluginsSettingsPage.xaml
ClassIsland/Views/SettingPages/PluginsSettingsPage.xaml.cs

效果：
https://github.com/user-attachments/assets/ee01fdf7-5c67-4b82-8d0f-29e3179e98e0

支持在插件界面拖入cipx文件安装插件

---

ClassIsland/Views/ProfileSettingsWindow.xaml.cs

想参与ci的开发，但是看了半天代码还是没啥头绪。也没摸清楚项目的结构，运行的过程。C#的基础也不是很好，读下去总是卡壳。wpf也没看明白，VS的设计器完全用不来。总之是太菜了。但是俗话说得好，菜就多练，不急慢慢来。
总之是先pr一下混个contributor也是很不错了，~~可以和老师吹嘘我也参与了ci的开发了。~~
最后感谢一下ci的开发者们！

feat: 重复添加行动提示

---

ClassIsland/Controls/NotificationProviders/ClassNotificationProviderSettingsControl.xaml
ClassIsland/Models/AttachedSettings/ClassNotificationAttachedSettings.cs
ClassIsland/Models/IClassNotificationSettings.cs
ClassIsland/Models/NotificationProviderSettings/ClassNotificationSettings.cs
ClassIsland/Services/NotificationProviders/ClassNotificationProvider.cs

feat: 户外课程全局提醒 第二次提交

---

ClassIsland/Services/NotificationProviders/ClassNotificationProvider.cs

在 PR #875 中，`ClassIsland/Services/NotificationProviders/ClassNotificationProvider.cs#L76-L134` 存在 `Complex Method` 的提示
于是把这一段重构了一下 应当可以解决问题

Refactor: 重写ClassNotificationProvider

---

ClassIsland/Controls/Components/WeatherComponentSettingsControl.xaml
ClassIsland/Controls/NotificationProviders/ClassNotificationProviderControl.xaml.cs
ClassIsland/Helpers/TimeSpanFormatHelper.cs

此拉取请求包含对 `ClassIsland` 项目中用户界面和时间跨度格式化的改进。最重要的更改包括对 `WeatherComponentSettingsControl.xaml` 文件的更新以及对两个文件中时间跨度格式化逻辑的修改。
* [`ClassIsland/Controls/Components/WeatherComponentSettingsControl.xaml`](diffhunk://#diff-3696534336a588858b5736d62cb5fae1a3e410ec46d870a1cb879202f3ad7f41L50-R50)：将 `ComboBoxItem` 的文本从“当使用默认图标时”更改为“仅当没有对应图标时”，以易于理解。
* [`ClassIsland/Controls/NotificationProviders/ClassNotificationProviderControl.xaml.cs`](diffhunk://#diff-cbfbe40d4dcfa855d7df5723527908549e25adcfbb122faf22ef8012de8be67bL134-R138)：改进了 `FormatTimeSpan` 方法，使其能够根据秒的存在情况有条件地格式化分钟。
* [`ClassIsland/Helpers/TimeSpanFormatHelper.cs`](diffhunk://#diff-9de14c3d306394fabdabf26d11524645a695a7c308f55e69c9c88a027c76a2e1R19-R28)：增强了 `Format` 方法，使其能够根据秒的存在情况有条件地格式化分钟。

feat: 优化部分文本表述

---

ClassIsland/Controls/Components/CountDownComponent.xaml
ClassIsland/Controls/Components/CountDownComponentSettingsControl.xaml
ClassIsland/Models/ComponentSettings/CountDownComponentSettings.cs

这个 PR 是 #1008 的重新提交
该 PR 提交到 `dev` 分支

feat: 倒计时连接词新增“仅剩”选项

---

ClassIsland/Controls/Components/WeatherComponent.xaml
ClassIsland/Converters/WindDirectionConverter.cs

fix: 天气简报风向偏转180°

---

.idea/.idea.ClassIsland/.idea/CopilotChatHistory.xml
.idea/.idea.ClassIsland/.idea/MarsCodeWorkspaceAppSettings.xml
.idea/.idea.ClassIsland/.idea/vcs.xml
.vscode/launch.json
.vscode/tasks.json
ClassIsland.PluginSdk/ClassIsland.PluginSdk.targets
ClassIsland/MainWindow.xaml

1. **UI虚拟化优化**
将`<ItemsControl>`的面板从`StackPanel`替换为`VirtualizingStackPanel`，并启用容器回收机制：
```xml:/f:/CodeProjects/ClassIsland/ClassIsland/MainWindow.xaml
<ItemsControl.ItemsPanel>
<ItemsPanelTemplate>
<VirtualizingStackPanel VirtualizationMode="Recycling"/>
</ItemsPanelTemplate>
</ItemsControl.ItemsPanel>
```
2. **动画性能优化**
将复杂的`DoubleAnimationUsingKeyFrames`动画简化为`DoubleAnimation`，并修复`EasingFunction`语法错误：
```xml:/f:/CodeProjects/ClassIsland/ClassIsland/MainWindow.xaml
<DoubleAnimation Storyboard.TargetProperty="Opacity" From="0" To="1" Duration="0:0:0.3">
<DoubleAnimation.EasingFunction>
<CircleEase EasingMode="EaseOut"/>
</DoubleAnimation.EasingFunction>
</DoubleAnimation>
```
3. **数据绑定优化**
禁用`CollectionViewSource`的实时分组和排序功能，减少不必要的UI更新： …

perf: 优化UI渲染性能，启用虚拟化并简化动画

---

ClassIsland/Views/SettingPages/AboutSettingsPage.axaml.cs

feat: 复制诊断信息

---

ClassIsland/Services/WeatherService.cs

feat: 支持按内容排除天气预警

---

ClassIsland/Helpers/ShortcutHelpers.cs
ClassIsland/Views/SettingsWindowNew.axaml
ClassIsland/Views/SettingsWindowNew.axaml.cs
ClassIsland/Views/WelcomeWindow.axaml.cs

- 更多的快捷方式创建菜单
鉴于 `WelcomeWindow.axaml.cs` 未实现其他平台创建「快捷方式」，故本 pr 未实现其他平台的逻辑，只做了隐藏菜单项。
还请各位开发者测试，引导修复。
刚刚那个pr选错目标分支了

更多的快捷方式创建菜单

---

CONTRIBUTING.md
README.md

此 Pull Request 主要修复以下问题：
- README.md 中，CSES 仓库地址未更新
- CONTRIBUTING.md 中，文字与行内代码块间未添加空格

doc: 更新 README 中的 CSES 仓库地址，优化贡献指南排版
